# ============================================
# Antigravity Life OS - Project Initializer (Windows)
# ============================================
# Usage: .\init-project.ps1 -ProjectName "my-app" -Type "dev"

param(
    [Parameter(Mandatory=$true, Position=0)]
    [string]$ProjectName,
    
    [Parameter(Mandatory=$false)]
    [ValidateSet("dev", "creative", "life")]
    [string]$Type = "dev"
)

$WorkspaceRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ProjectPath = Join-Path $WorkspaceRoot "projects" $ProjectName

Write-Host "🚀 Initializing project: $ProjectName" -ForegroundColor Blue
Write-Host "   Type: $Type"
Write-Host "   Path: $ProjectPath"
Write-Host ""

# Create project structure
$folders = @("src", "tests", "docs", "spec", "research", "resources\mockups", "tracks")
foreach ($folder in $folders) {
    $path = Join-Path $ProjectPath $folder
    New-Item -ItemType Directory -Path $path -Force | Out-Null
}
Write-Host "✓ Created directory structure" -ForegroundColor Green

# Copy appropriate template
$libraryPath = Join-Path $WorkspaceRoot "library"
switch ($Type) {
    "dev" {
        Copy-Item (Join-Path $libraryPath "dev-templates\PRP_TEMPLATE.md") (Join-Path $ProjectPath "docs\PRP.md")
        Write-Host "✓ Copied PRP template" -ForegroundColor Green
    }
    "creative" {
        Copy-Item (Join-Path $libraryPath "creative-templates\CONTENT_TEMPLATE.md") (Join-Path $ProjectPath "docs\CONTENT.md")
        Write-Host "✓ Copied Content template" -ForegroundColor Green
    }
    "life" {
        Copy-Item (Join-Path $libraryPath "life-templates\WEEKLY_PLANNER.md") (Join-Path $ProjectPath "docs\PLANNER.md")
        Write-Host "✓ Copied Planner template" -ForegroundColor Green
    }
}

# Copy CLAUDE.md
$claudeTemplate = Join-Path $libraryPath "claude-templates\CLAUDE.md"
if (Test-Path $claudeTemplate) {
    Copy-Item $claudeTemplate (Join-Path $ProjectPath "CLAUDE.md")
    Write-Host "✓ Copied CLAUDE.md" -ForegroundColor Green
}

# Create README
$readme = @"
# $ProjectName

**Type:** $Type
**Created:** $(Get-Date -Format "yyyy-MM-dd")
**Status:** Initial

---

## Overview
[プロジェクトの概要をここに記載]

## Structure
``````
$ProjectName/
├── src/              # ソースコード
├── tests/            # テスト
├── docs/             # PRP等ドキュメント
├── spec/             # 実装プラン
├── research/         # 調査結果
├── resources/mockups # デザイン
└── tracks/           # 並列実行トラック
``````

## Quick Start
1. ``docs/PRP.md`` に要件を記載
2. PMに設計依頼
3. 並列実装開始

---
*Generated by Antigravity Life OS*
"@

$readme | Out-File -FilePath (Join-Path $ProjectPath "README.md") -Encoding UTF8
Write-Host "✓ Created README.md" -ForegroundColor Green

# Create .gitkeep files
$gitkeepFolders = @("src", "tests", "spec", "research", "tracks")
foreach ($folder in $gitkeepFolders) {
    $keepPath = Join-Path $ProjectPath $folder ".gitkeep"
    New-Item -ItemType File -Path $keepPath -Force | Out-Null
}

Write-Host ""
Write-Host "✅ Project initialized successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. cd $ProjectPath"
Write-Host "  2. Edit docs\PRP.md with your requirements"
Write-Host "  3. Start development with Agent Guild"
