#!/bin/bash
# ============================================
# Antigravity Life OS - Project Initializer
# ============================================
# Usage: ./init-project.sh <project-name> [--type dev|creative|life]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
PROJECT_TYPE="dev"
WORKSPACE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Parse arguments
if [ -z "$1" ]; then
    echo -e "${RED}Error: Project name is required${NC}"
    echo "Usage: ./init-project.sh <project-name> [--type dev|creative|life]"
    exit 1
fi

PROJECT_NAME="$1"
shift

while [[ $# -gt 0 ]]; do
    case $1 in
        --type)
            PROJECT_TYPE="$2"
            shift 2
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

PROJECT_PATH="${WORKSPACE_ROOT}/projects/${PROJECT_NAME}"

echo -e "${BLUE}🚀 Initializing project: ${PROJECT_NAME}${NC}"
echo "   Type: ${PROJECT_TYPE}"
echo "   Path: ${PROJECT_PATH}"
echo ""

# Create project structure
mkdir -p "${PROJECT_PATH}/src"
mkdir -p "${PROJECT_PATH}/tests"
mkdir -p "${PROJECT_PATH}/docs"
mkdir -p "${PROJECT_PATH}/spec"
mkdir -p "${PROJECT_PATH}/resources/mockups"
mkdir -p "${PROJECT_PATH}/tracks"

# Copy appropriate template
case $PROJECT_TYPE in
    dev)
        cp "${WORKSPACE_ROOT}/library/dev-templates/PRP_TEMPLATE.md" "${PROJECT_PATH}/docs/PRP.md"
        echo -e "${GREEN}✓${NC} Copied PRP template"
        ;;
    creative)
        cp "${WORKSPACE_ROOT}/library/creative-templates/CONTENT_TEMPLATE.md" "${PROJECT_PATH}/docs/CONTENT.md"
        echo -e "${GREEN}✓${NC} Copied Content template"
        ;;
    life)
        cp "${WORKSPACE_ROOT}/library/life-templates/WEEKLY_PLANNER.md" "${PROJECT_PATH}/docs/PLANNER.md"
        echo -e "${GREEN}✓${NC} Copied Planner template"
        ;;
esac

# Copy CLAUDE.md for Claude Code
if [ -f "${WORKSPACE_ROOT}/library/claude-templates/CLAUDE.md" ]; then
    cp "${WORKSPACE_ROOT}/library/claude-templates/CLAUDE.md" "${PROJECT_PATH}/CLAUDE.md"
    echo -e "${GREEN}✓${NC} Copied CLAUDE.md"
fi

# Copy .claude directory if exists
if [ -d "${WORKSPACE_ROOT}/library/claude-templates/.claude" ]; then
    cp -r "${WORKSPACE_ROOT}/library/claude-templates/.claude" "${PROJECT_PATH}/.claude"
    echo -e "${GREEN}✓${NC} Copied .claude directory"
fi

# Create project README
cat > "${PROJECT_PATH}/README.md" << EOF
# ${PROJECT_NAME}

**Type:** ${PROJECT_TYPE}
**Created:** $(date +%Y-%m-%d)
**Status:** Initial

---

## Overview
[プロジェクトの概要をここに記載]

## Structure
\`\`\`
${PROJECT_NAME}/
├── src/        # ソースコード
├── tests/      # テスト
├── docs/       # PRP等ドキュメント
├── spec/       # 実装プラン
└── tracks/     # 並列実行トラック
\`\`\`

## Quick Start
1. \`docs/PRP.md\` に要件を記載
2. Architect-Plan に設計依頼
3. 並列実装開始

---
*Generated by Antigravity Life OS*
EOF

echo -e "${GREEN}✓${NC} Created README.md"

# Create .gitkeep files
touch "${PROJECT_PATH}/src/.gitkeep"
touch "${PROJECT_PATH}/tests/.gitkeep"
touch "${PROJECT_PATH}/spec/.gitkeep"
touch "${PROJECT_PATH}/tracks/.gitkeep"

echo ""
echo -e "${GREEN}✅ Project initialized successfully!${NC}"
echo ""
echo "Next steps:"
echo "  1. cd ${PROJECT_PATH}"
echo "  2. Edit docs/PRP.md with your requirements"
echo "  3. Start development with Agent Guild"
